server:
  port: 8090

spring:
  application:
    name: wangque
  datasource:
    username: root
    password: Aa123456
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/wangque?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 给pojo实体类起别名
  type-aliases-package: com.asule.wangque.entity
  # 接口的配置文件的位置
  mapper-locations: classpath:mapper/*.xml
